### ISSUE TITLE
Questions to resolve for naming candidates

### ISSUE THREAD

**Issue by kuriwaki** [kuriwaki/cces_candidates#1]
- [x] How to code new names

Two word first names 

- [x] Two word first names where the second is used. https://en.wikipedia.org/wiki/Burgess_Owens  **OWENS, CLARENCE BURGESS**
- [x] When to abbreviate a middlename? e.g. BURGESS, MICHAEL C.  https://en.wikipedia.org/wiki/Michael_C._Burgess, **use full middlename -- but maybe not bother**

Discrepancies in names - some related to the 2018 lack of standardization.  **Shiro and Jim will handle 2018 first**

- [x] SALUD O. CARBAJAL/SALUD CARBAJAL
- [x] PETERS, SCOTT/PETERS, SCOTT H.
- [x] RUTHERFORD, JOHN H./ RUTHERFORD, JOHN
- [x] MOOLENAAR, JOHN R./MOOLENAAR, JOHN

Multiple last names

- [x] ROCHESTER, LISA BLUNT/ BLUNT ROCHESTER, LISA --> **`BLUNT ROCHESTER, LISA LATRELLE`**
- [x] wikipedia says Abigail Davis Spanberger (nee Davis) but congress says  Abigail D. Spanberger --> **SPANBERGER, ABIGAIL ANNE DAVIS**

Hyphens in existing names - **Keep the hyphenated names**

- [x] ROYBAL-ALLARD, LUCILLE. 
- [x] CAMPA-NAJJAR, AMMAR
- [x] DIAZ-BALART, MARIO

Candidates who only had given names in parentheses - **Find the official name from other sources**

- [x] ROBINSON, (SCOTTY). 
- [x] HASTY, (MATT). 

Non-top two parties 

- [x] Fusion / cross-listed candidates: `FAMILIES, WORKING`.  **Keep in D and WF in separate rows**, then we will might make a third row with "party = D, WF" and total
- [x] SCATTER, WRITE-IN --> **will drop** in final dataset. But in Nevada, "None of the above" is actually on the ballot and might come in second place. So code as `[NONE OF ABOVE]`. **No House observations are "None of the above"**

**Comment by jcha1997** [comment]
Discrepancies in names - some related to the 2018 lack of standardization

- [ ] SALUD O. CARBAJAL/SALUD CARBAJAL
- [ ] PETERS, SCOTT/PETERS, SCOTT H.
- [ ] ROCHESTER, LISA BLUNT/ BLUNT ROCHESTER, LISA
- [ ] RUTHERFORD, JOHN H./ RUTHERFORD, JOHN
- [ ] MOOLENAAR, JOHN R./MOOLENAAR, JOHN

Hyphens in existing names - Should we correct to standardize to exclude hyphens? 

- [ ] ROYBAL-ALLARD, LUCILLE
- [ ] CAMPA-NAJJAR, AMMAR
- [ ] DIAZ-BALART, MARIO

Candidates who only had given names in parentheses - Should we pull from campaign websites? 

- [ ] ROBINSON, (SCOTTY)
- [ ] HASTY, (MATT)

Misc Issues
- [ ] What to do with candidates with simply party names? e.g. FAMILIES, WORKING

**Comment by kuriwaki** [comment]
Thanks @jcha1997
