### ISSUE TITLE
Shortening party for data outside Jim's

### ISSUE THREAD

**Issue by kuriwaki** [kuriwaki/cces_candidates#24]
i.e. `party_formal` vs. `party`. That stacking happens in 03. However, all the party stuff is happening in 02 now. Can we try to move the party shortening to 03? I don't want to repeat it twice.

**Comment by jcha1997** [comment]
See https://github.com/kuriwaki/cces_candidates/commit/d52b3def641b897e1d43fdf82daa7d3f86f196c5 - I moved the party recodes, including your fusion candidate fixes here. Let me know if this works for you.

**Comment by kuriwaki** [comment]
Generally what I was thinking, but `guide/Tables/cands/won_H_gen.tex` no longer looks right so we need to fix something. Maybe about the order?

**Comment by kuriwaki** [comment]
that correction (in the top of 03) makes sense.
