### ISSUE TITLE
Corrections on incumbency

### ISSUE THREAD

**Issue by bwilker** [kuriwaki/cces_candidates#30]
Two gubernatorial candidates are incorrectly labeled for incumbency (inc).
Jan Brewer, AZ 2010, is not labeled as an incumbent and should be (coded a 3, not 0)
Julianne Murray, DE 2020, is labeled as an incumbent and should not be (coded a 0, not 1)

**Comment by jcha1997** [comment]
Thanks for bringing this to our attention. This should be fixed in https://github.com/kuriwaki/cces_candidates/commit/0ae113caa7f5c2907ba8fa85160481feadda5cfd. We will push these fixes and other updates in v2.

**Comment by kuriwaki** [comment]
Thank you @bwilker.  We have uploaded v2 to dataverse with this and other fixes.   https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DGDRDT
