### ISSUE TITLE
Runoffs and special elections are uniquely identifiable and documented

### ISSUE THREAD

**Issue by jcha1997** [kuriwaki/cces_candidates#6]

**Comment by kuriwaki** [comment]
- [ ] Fix Loeffler and Warnock candidatevotes (off by 10x)
- [ ] Document in codebook that we only show the deciding race (January 5 in Georgia 2020), and do not show the "pre-runoff". 
- [ ] Add a new column called `runoff \in "R", ""`. Add GA, LA

**Comment by jcha1997** [comment]
I put the section about including deciding races and no pre-runoff races in the runoff variable in the guide. Let me know if you think that is an appropriate place for this.

**Comment by kuriwaki** [comment]
e0799ff6b01065e68c7a59fdee352bfde2308a5c looks good. I usually like to add an example (e.g. in 2020 Georgia Senate, the November election is _not_ included but the January one is), but we can add as we finalize

**Comment by jcha1997** [comment]
https://github.com/kuriwaki/cces_candidates/commit/093dc55fae4a9cac761cc3fbbe2a5908e96a9698 includes the reference to the 2020 Georgia contests in the runoff variable.
